/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as fse from 'fs-extra';
import * as os from 'os';
import * as path from 'path';
import { func, funcWatchProblemMatcher, gitignoreFileName, hostFileName, hostStartCommand, localSettingsFileName, ProjectRuntime, proxiesFileName, TemplateFilter } from '../../constants';
import { ILocalAppSettings } from '../../LocalAppSettings';
import { confirmOverwriteFile, writeFormattedJson } from "../../utils/fs";
import { ProjectCreatorBase } from './ProjectCreatorBase';

// https://github.com/github/gitignore/blob/master/Node.gitignore
// tslint:disable-next-line:no-multiline-string
const gitignore: string = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# next.js build output
.next

# nuxt.js build output
.nuxt

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# Azure Functions artifacts
bin
obj
appsettings.json
local.settings.json

# TypeScript output
dist
out
`;

/**
 * Base class for all projects based on a simple script (i.e. JavaScript, C# Script, Bash, etc.) that don't require compilation
 */
export class ScriptProjectCreatorBase extends ProjectCreatorBase {
    public static defaultRuntime: ProjectRuntime = ProjectRuntime.v1;
    // Default template filter to 'All' since preview languages have not been 'verified'
    public readonly templateFilter: TemplateFilter = TemplateFilter.All;
    public readonly functionsWorkerRuntime: string | undefined;

    protected funcignore: string[] = ['.git*', '.vscode', 'local.settings.json', 'test'];

    public getTasksJson(): {} {
        return {
            version: '2.0.0',
            tasks: [
                {
                    type: func,
                    command: hostStartCommand,
                    problemMatcher: funcWatchProblemMatcher,
                    isBackground: true
                }
            ]
        };
    }

    public async onCreateNewProject(): Promise<void> {
        const hostJsonPath: string = path.join(this.functionAppPath, hostFileName);
        if (await confirmOverwriteFile(hostJsonPath)) {
            const hostJson: {} = {
                version: '2.0'
            };
            await writeFormattedJson(hostJsonPath, hostJson);
        }

        const localSettingsJsonPath: string = path.join(this.functionAppPath, localSettingsFileName);
        if (await confirmOverwriteFile(localSettingsJsonPath)) {
            const localSettingsJson: ILocalAppSettings = {
                IsEncrypted: false,
                Values: {
                    AzureWebJobsStorage: ''
                }
            };

            if (this.functionsWorkerRuntime) {
                // tslint:disable-next-line:no-non-null-assertion
                localSettingsJson.Values!.FUNCTIONS_WORKER_RUNTIME = this.functionsWorkerRuntime;
            }

            await writeFormattedJson(localSettingsJsonPath, localSettingsJson);
        }

        const proxiesJsonPath: string = path.join(this.functionAppPath, proxiesFileName);
        if (await confirmOverwriteFile(proxiesJsonPath)) {
            const proxiesJson: {} = {
                // tslint:disable-next-line:no-http-string
                $schema: 'http://json.schemastore.org/proxies',
                proxies: {}
            };
            await writeFormattedJson(proxiesJsonPath, proxiesJson);
        }

        const gitignorePath: string = path.join(this.functionAppPath, gitignoreFileName);
        if (await confirmOverwriteFile(gitignorePath)) {
            await fse.writeFile(gitignorePath, gitignore);
        }

        const funcIgnorePath: string = path.join(this.functionAppPath, '.funcignore');
        if (await confirmOverwriteFile(funcIgnorePath)) {
            await fse.writeFile(funcIgnorePath, this.funcignore.sort().join(os.EOL));
        }
    }

    public async onInitProjectForVSCode(): Promise<void> {
        // nothing to do here
    }
}
