/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { type Site } from '@azure/arm-appservice';
import { DomainNameLabelScope, tryGetWebApp } from '@microsoft/vscode-azext-azureappservice';
import { runWithTestActionContext } from '@microsoft/vscode-azext-utils';
import * as assert from 'assert';
import { getRandomHexString } from '../../src/utils/fs';
import { longRunningTestsEnabled } from '../global.test';
import { getCachedTestApi } from '../utils/testApiAccess';
import { resourceGroupsToDelete, testClient } from './global.nightly.test';

/**
 * Tests for Domain Name Label Scope functionality in function app creation.
 *
 * DomainNameLabelScope quick pick options:
 * - Tenant (TenantReuse): Secure unique default hostname
 * - Legacy: Global default hostname
 *
 * In basic create, the domain scope is automatically set to Tenant (no prompt)
 * In advanced create, the user is prompted to select between Tenant or Legacy
 */
suite('Domain Name Label Scope', function (this: Mocha.Suite): void {
    this.timeout(10 * 60 * 1000);

    let location: string;
    let rgName: string;

    suiteSetup(async function (this: Mocha.Context): Promise<void> {
        if (!longRunningTestsEnabled) {
            this.skip();
        }

        rgName = getRandomHexString();
        resourceGroupsToDelete.push(rgName);
        location = 'West US 2';
    });

    test('Basic creation uses Tenant scope by default', async () => {
        const appName = getRandomHexString();
        const testApi = getCachedTestApi();

        const testInputs: (string | RegExp)[] = [
            location,       // Location
            appName,        // App name
            /\.net/i,       // Stack
            /secrets/i,     // Auth type
        ];

        await runWithTestActionContext('createFunctionApp', async context => {
            await context.ui.runWithInputs(testInputs, async () => {
                await testApi.commands.createFunctionApp(context);
            });
        });

        const createdApp: Site | undefined = await tryGetWebApp(testClient, appName, appName);
        assert.ok(createdApp, 'Function app should be created');
        assert.equal(createdApp.autoGeneratedDomainNameLabelScope, DomainNameLabelScope.Tenant);
    });

    test('Advanced creation with Tenant scope', async () => {
        const appName = getRandomHexString();
        const saName = getRandomHexString().toLowerCase();
        const miName = getRandomHexString();
        const aiName = getRandomHexString();
        const testApi = getCachedTestApi();

        const testInputs: (string | RegExp)[] = [
            location,                                   // Location
            '$(plus) Create new resource group',        // Resource Group
            rgName,                                     // RG name
            /secure.*unique|tenant/i,                   // Domain scope (Tenant)
            appName,                                    // App name
            'Flex Consumption',                         // Hosting plan
            /\.net/i,                                   // Stack
            '4096',                                     // Instance memory
            '100',                                      // Max instances
            'Managed identity',                         // Auth type
            '$(plus) Create new user-assigned identity', // Create new identity
            miName,                                     // Identity name
            '$(plus) Create new storage account',       // Storage account
            saName,                                     // SA name
            '$(plus) Create new Application Insights resource', // App Insights
            aiName,                                     // AI name
        ];

        await runWithTestActionContext('createFunctionAppAdvanced', async context => {
            await context.ui.runWithInputs(testInputs, async () => {
                await testApi.commands.createFunctionAppAdvanced(context);
            });
        });

        const createdApp: Site | undefined = await tryGetWebApp(testClient, rgName, appName);
        assert.ok(createdApp, 'Function app should be created with Tenant domain scope');
        assert.equal(createdApp.autoGeneratedDomainNameLabelScope, DomainNameLabelScope.Tenant);
    });

    test('Advanced creation with Legacy scope', async () => {
        const appName = getRandomHexString();
        const saName = getRandomHexString().toLowerCase();
        const miName = getRandomHexString();
        const aiName = getRandomHexString();
        const testApi = getCachedTestApi();

        const testInputs: (string | RegExp)[] = [
            location,                                   // Location
            rgName,                                     // Use existing RG
            /global.*default|legacy/i,                  // Domain scope (Legacy)
            appName,                                    // App name
            'Flex Consumption',                         // Hosting plan
            /\.net/i,                                   // Stack
            '4096',                                     // Instance memory
            '100',                                      // Max instances
            'Managed identity',                         // Auth type
            '$(plus) Create new user-assigned identity', // Create new identity
            miName,                                     // Identity name
            '$(plus) Create new storage account',       // Storage account
            saName,                                     // SA name
            '$(plus) Create new Application Insights resource', // App Insights
            aiName,                                     // AI name
        ];

        await runWithTestActionContext('createFunctionAppAdvanced', async context => {
            await context.ui.runWithInputs(testInputs, async () => {
                await testApi.commands.createFunctionAppAdvanced(context);
            });
        });

        const createdApp: Site | undefined = await tryGetWebApp(testClient, rgName, appName);
        assert.ok(createdApp, 'Function app should be created with Global domain scope');
        assert.equal(createdApp.autoGeneratedDomainNameLabelScope, undefined);
    });
});
