/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { nonNullProp } from '@microsoft/vscode-azext-utils';
import { type IFunctionAppWizardContext } from '../IFunctionAppWizardContext';

/**
 * Maps the wizard context's language/runtime to the AZD service language identifier.
 */
function getAzdLanguage(context: IFunctionAppWizardContext): string {
    const workerRuntime: string = context.newSiteStack?.minorVersion.stackSettings.linuxRuntimeSettings?.appSettingsDictionary?.FUNCTIONS_WORKER_RUNTIME
        ?? context.newSiteStack?.minorVersion.stackSettings.windowsRuntimeSettings?.appSettingsDictionary?.FUNCTIONS_WORKER_RUNTIME
        ?? context.newSiteStack?.stack.value
        ?? 'node';

    if (workerRuntime === 'node') {
        return 'js';
    } else if (workerRuntime === 'python') {
        return 'py';
    } else if (workerRuntime.startsWith('dotnet')) {
        return 'csharp';
    } else if (workerRuntime === 'java') {
        return 'java';
    }

    return 'js';
}

/**
 * Generates the azure.yaml manifest content for AZD provisioning.
 * This file tells AZD about the project structure and which service to provision.
 */
export function generateAzdYaml(context: IFunctionAppWizardContext): string {
    const siteName = nonNullProp(context, 'newSiteName');
    const language = getAzdLanguage(context);

    return `# Auto-generated by Azure Functions VS Code extension
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: ${siteName}
metadata:
  template: vscode-azurefunctions-generated
services:
  api:
    project: .
    host: function
    language: ${language}
`;
}
