# Trigger the build whenever `main` or `rel/*` is updated
trigger:
  - main
  - rel/*

# Disable PR trigger
pr: none

# Scheduled nightly build of `main`
schedules:
  - cron: "0 0 * * *"
    displayName: Nightly scheduled build
    always: false # Don't rebuild if there haven't been changes
    branches:
      include:
        - main

parameters:
  - name: enableLongRunningTests
    displayName: Enable Long Running Tests
    type: boolean
    default: true

resources:
  repositories:
    # Use the shared templates from microsoft/vscode-azuretools
    - repository: azExtTemplates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/testFeed # TODO: revert
      endpoint: GitHub-AzureTools # The service connection to use when accessing this repository

variables:
  # Pick up shared AZCode variables
  - template: azdo-pipelines/azcode.variables.yml@azExtTemplates
  - name: feedBaseUrl
    value: https://devdiv.pkgs.visualstudio.com/DevDiv/_packaging/azcode

extends:
  template: azdo-pipelines/1es-mb-main.yml@azExtTemplates # Use the main build template
  parameters:
    npmFeed: ${{ variables.npmFeed }}
    additionalSetupSteps:
      - task: UseDotNet@2
        displayName: Install .NET 9.0
        inputs:
          version: 9.0.x
      - template: configure-feed-mirrors.yml
    ${{ if eq(parameters.enableLongRunningTests, true) }}:
      testARMServiceConnection: ${{ variables.testARMServiceConnection }}
