/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { type Site, type StringDictionary } from '@azure/arm-appservice';

/**
 * Maps the FUNCTIONS_WORKER_RUNTIME value to the AZD language identifier.
 */
function getAzdLanguageFromRuntime(workerRuntime: string): string {
    switch (workerRuntime.toLowerCase()) {
        case 'node':
            return 'js';
        case 'python':
            return 'py';
        case 'dotnet':
        case 'dotnet-isolated':
            return 'csharp';
        case 'java':
            return 'java';
        default:
            return 'js';
    }
}

/**
 * Generates an azure.yaml file from an existing Function App's site envelope and app settings.
 * The generated YAML uses `resourceName` to tell azd which existing Function App to deploy to,
 * and `project` to point to the local source code for deployment.
 *
 * @param site The ARM Site object from the function app
 * @param appSettings The app settings (StringDictionary) from list application settings
 * @param deployFsPath Absolute path to the local deployment folder (forward-slash separated)
 */
export function generateAzdYamlFromSite(site: Site, appSettings: StringDictionary, deployFsPath: string): string {
    const siteName = site.name ?? 'unknown';

    // Determine worker runtime from app settings or flex config
    const workerRuntime =
        appSettings?.properties?.FUNCTIONS_WORKER_RUNTIME ??
        site.functionAppConfig?.runtime?.name ??
        'node';

    const language = getAzdLanguageFromRuntime(workerRuntime);

    // Normalize path separators for YAML (use forward slashes)
    const normalizedPath = deployFsPath.replace(/\\/g, '/');

    return `# Auto-generated by Azure Functions VS Code extension (deploy with AZD)
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: ${siteName}
metadata:
  template: vscode-azurefunctions-deploy
services:
  api:
    project: ${normalizedPath}
    host: function
    language: ${language}
    resourceName: ${siteName}
`;
}
