steps:
- task: Npm@1
  displayName: 'Lint'
  inputs:
    command: custom
    customCommand: run lint

- task: ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'
  condition: not(variables['System.PullRequest.IsFork'])
