name: Bump version after release

# Run when release is published, or manually triggered
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Bump version
        id: bump
        uses: alexweininger/bump-prerelease-version@91183ecfa908d49e9e7c1c62e9c781a49aa7c307 # v0.1.1

      - name: Create pull request
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          title: ${{ env.MESSAGE }}
          body: Automatically created by ${{ env.RUN_LINK }}
          commit-message: ${{ env.MESSAGE }}
          branch: bot/bump-${{ steps.bump.outputs.new-version }}
          base: main
          author: GitHub <noreply@github.com>
          token: ${{ secrets.PAT_GITHUB }}
        env:
          RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          MESSAGE: Bump version after release
